DAOS-623 build: Create a simple RPM package
daos-stack/fused pull request #1
Opened 2024-02-23 15:21 UTC by jolivier23

Makes the simplest of RPM packages for fused.
Renames the static library and include dir from
fuse3 to fused to avoid any conflict with
standard libfuse3.a.

2024-03-18 18:29 UTC, jolivier23 commented
@brianjmurrell can I pick your brain on this one?

But before I do so, here are the reasons for doing a fork of fuse
1. the upstream libfuse releases at too slow a rate
2. FUSE provides terrrible performance out of the box and we want to experiment and possibly ship a custom kernel module.  As such, we would want to customize libfuse as well.  We could do the latter via patches but I wanted to have something that would not mess up other fuse file systems executing on the same node.

My builder renames fuse3 to fused so the libraries provided by the fused package won't conflict with libraries installed by the upstream library.

I can build both debian and rpm packages locally, I'm just trying to get the basic RPM/deb build working in Jenkins.  For this purpose, I used the raft module as an example since it also is a fork where the code resides in the same repository.  But it doesn't seem to be working for various reasons and without any visibility into Jenkins, I'm finding my ability to fix it limited.

I wanted to not have to bug you at all til I had it working but failed.

2024-06-04 22:51 UTC, brianjmurrell commented
Do you have a reference as to how/where this package is used?

2024-06-05 13:27 UTC, brianjmurrell requested changes
Just -1 until the purpose and use is more clearly understood.

2024-06-05 16:19 UTC, jolivier23 commented
> Do you have a reference as to how/where this package is used?

Yeah, the idea is to move our fuse in this direction for a couple of reasons

1. there are other users of fuse so building fuse that everyone else uses seems risky
2. Gives us the ability to maintain our own fork with patches that upstream may not take that are specific to daos.

Here is a proof of concept patch to DAOS
https://github.com/daos-stack/daos/pull/14077

That patch can't be landed until we land this and then figure out proper versioning.

2024-06-05 19:06 UTC, brianjmurrell requested changes
You have rpmlint errors/warning that need to be resolved for a distributed package.

You also don't really want githash info included in the Release if you are building from a tag:

```
$ rpm -q --provides fused-1.0.0-1.2014.g0303197.el8.x86_64.rpm 
fused = 1.0.0-1.2014.g0303197.el8
fused(x86-64) = 1.0.0-1.2014.g0303197.el8
```

These should look like:
```
$ rpm -q --provides fused-1.0.0-1.el8.x86_64.rpm 
fused = 1.0.0-1.el8
fused(x86-64) = 1.0.0-1.el8
```

2024-06-05 19:06 UTC, brianjmurrell commented on .gitignore
> -Makefile
Why don't we want to ignore this file?  It's autogenerated from `Makefile.in` isn't it?

2024-06-05 19:06 UTC, brianjmurrell commented on Jenkinsfile
> +/* Copyright (C) 2019 Intel Corporation
Copyright update here?

2024-06-05 19:06 UTC, brianjmurrell commented on debian/rules
> +	find include -type f -name "*" -exec sed -i 's/fuse3/fused/g' {} ';'
Is the `-name *` redundant?  Apart from that, this would be much more efficient:

```suggestion
	find lib -type f -name "*" -print0 | xargs -0r sed -i 's/fuse3/fused/g' {} ';'
	find include -type f -name "*" -print0 | xargs -0r  sed -i 's/fuse3/fused/g' {} ';'
```

as it only runs `sed` as many times is as necessary to fit within command-line length limits and passes as many filenames to a single `sed` command that fits within the limit.

But that said (heh, see what I did there?) isn't this kind of substitution something that should be done in the [libfuse fork](https://github.com/daos-stack/fused) so that people building that from source don't also have to know to do this `s///`?

2024-06-05 19:06 UTC, brianjmurrell commented on debian/rules
> +	sed -i 's/fuse3/fused/g' meson_options.txt
Ditto on doing this in the fork.

2024-06-05 19:06 UTC, brianjmurrell commented on fused.spec
> +find . -type f -name "*" -exec sed -i 's/fuse3/fused/g' {} ';'
Ditto on using `xargs` and doing it in the fork.

2024-12-20 02:55 UTC, merged